### ISSUE TITLE
This project's maintenance

### ISSUE THREAD

**Issue by dtantsur** [redhat-cip/hardware#47]
Hi @ErwanAliasr1 @fredericlepied,

Sorry for using issue tracker for question, but I'd like to (publicly) ask about the state of maintenance of this library. The thing is, we still rely on it in TripleO, but according to https://github.com/redhat-cip/hardware/pull/42#issuecomment-389483805 it essentially not maintained, and pull requests have not been merged since June. The last release is from year 2016.
Do you need help with maintaining the project? I can offer at least basic help with sorting out trivial pull requests and bug reports, and making releases. If you wish so, we can discuss transferring it to the OpenStack git/gerrit infrastructure.

Cheers,
Dmitry

/cc @tbreeds

**Comment by ErwanAliasr1** [comment]
I'm not very active on it. If you are still using it, feel free to help on this project.

**Comment by dtantsur** [comment]
In which form would you accept such help? Would you like some of us to process pull requests or completely take over the project? Would you be open to moving it to OpenStack Infra's Git and Gerrit?

**Comment by tbreeds** [comment]
I'd be happy to help process PRs and tag/create releases.   Or if desired help migrate this onto openstack infrastructure .

**Comment by tbreeds** [comment]
This isn't resolved but I believe that I'm able to process PRs and create releases now.

**Comment by ErwanAliasr1** [comment]
I'm almost back to the project because of my new activities.

**Comment by dtantsur** [comment]
@ErwanAliasr1 \o/ welcome back :)

Could you please try fixing the travis CI here? Or should we move python-hardware as an independent project under the openstack infrastructure and use gerrit/zuul/everything?

**Comment by juliakreger** [comment]
@ErwanAliasr1 One thing worth noting is that we can likely bring a few experts to bear in order to help resolve CI issues if the decision is to move this project to OpenStack's infrastructure and use gerrit/zuul.   We could also likely assist with review velocity in that context as well since the OpenStack baremetal project does generally create a list of patches each week to marshall contributors to review in gerrit.

**Comment by ErwanAliasr1** [comment]
@juliakreger I'm not so sure of the interest for this project to go in that infrastructure. I know we have to fix the CI here, but contributing via github is much easier for new comers. As this project is not openstack specific, I'm not really in the mind to move :(

**Comment by juliakreger** [comment]
@ErwanAliasr1 Okay. I actually feel github is harder to follow and use, but that is just me. :) Just know the offer is there if needed.

**Comment by ErwanAliasr1** [comment]
Thanks!

Le ven. 22 févr. 2019 à 22:28, Julia Kreger <notifications@github.com> a
écrit :

**Comment by tbreeds** [comment]
I'd like to close this as I think ion the last little while we've shown we can patch and create releases.

Thoughts?

**Comment by elfosardo** [comment]
The only concern I have right now is that it seems we still don't have a proper CI in place for the repo

**Comment by dtantsur** [comment]
It's a valid concern. We need to at least run pep8 and unit tests. If nobody is able to repair the travis CI, we should migrate to opendev and use its zuul.

**Comment by tbreeds** [comment]
Yup I agree.

We can't use zuul as a 3rd party as we don't quite meet the criteria to do that.  I tried to fix travis but I can't as I don't 'own' this repo and I'm not an admin in the github org (redhat-cip) so we're back to @ErwanAliasr1 or @fredericlepied fixing Travis to help with the functional CI side of things.

Another 'middle ground' option would be to create a new github org and transfer this repo into that then we'd have more options around who can do what.  I'd be able to fix Travis

**Comment by ErwanAliasr1** [comment]
@fredericlepied commit a fix for the travis part which was linked to the python 3.x update.

**Comment by elfosardo** [comment]
Is Travis actually fixed now?
I still have some concerns since apparently Travis doesn't have support for Ubuntu Bionic and there's no plan to add it [1].
It took them 2 years to release support for Xenial, just something should be taken into account, considering that basically everything is moving to Bionic and systemd is the new standard, to not mention all the updates to the packages and tools that are used by this repo scripts.

1. https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270/10

**Comment by tbreeds** [comment]
Looks like travis is fixed. with https://github.com/redhat-cip/hardware/pull/86/commits/3fa42431bf91f16d053ece65c97b146507800bdf \o/

I don't have a strong opinion about bionic vs xenial.

**Comment by elfosardo** [comment]
Hello, I'd like to revamp this thread.
First of all I'd like to thank all for the efforts in bringing back the Travis CI, although I strongly believe that Travis is very limited and not enough to properly cover the testing needs of the repo.
Also, it doesn't look like the project is getting the attention it needs and deserves.
I'd like to push one more time to consider the option to move the repo to opendev.org under the OpenStack Baremetal (ironic) umbrella, considering that it's very important for that project and strictly connected to the Ironic Python Agent.
Moreover, having the project there will drastically increase its visibility, and the newcomers will be supported by the entire community already behind the other projects connected to ironic.

**Comment by lebauce** [comment]
> considering that it's very important for that project and strictly connected to the Ironic Python Agent.

The Ironic Python Agent is just one user of this library, which was started way before.

**Comment by elfosardo** [comment]
@lebauce  that is absolutely true, and I didn't forget that, in fact.
Although I would like to point out that most of the improvements, changes and general maintenance in the last nine months come from work directly connected to the work done on the Ironic Python Agent, by people working in the Openstack community.
The latest release before v0.20.0 from March 2019, was done in June 2016, and again only because people from the Openstack community, me included, asked for it (and we were lucky to have Tony to help us).
As I see this repository right now is a very important piece of the BareMetal project in Openstack, having under the Openstack umbrella won't change anything for the other users, and actually I strongly believe it will help in improving it.

**Comment by ErwanAliasr1** [comment]
But most of the detection code is not from ironic people. Only refactoring.
I'd love to see more people contributing to the detection code which have
many weaknesses.

Le jeu. 18 juil. 2019 à 16:28, Riccardo Pittau <notifications@github.com> a
écrit :

**Comment by juliakreger** [comment]
@ErwanAliasr1 I don't think it is about time used, or who is working on and contributing specific features, but the body of contributors who are willing and presently able to contribute, maintain, and improve the code base. Github is seen as "open source" only through the perception of access, but in many corporations and institutions, explicit per project permission must be granted prior to contributing back due to legal and corporate governance compliance rules. It is sort of like being an employee of "Z Corporation" and asking management to contribute directly to competitor "Y Corporation" product. In the OpenStack community, and now larger OpenDev community, many corporations grant blanket permission for their employees and associates to contribute to anything within the OpenStack namespace or that is hosted by the OpenStack Foundation simply because those corporations have trust in the foundation's principals and the larger community.

**Comment by tbreeds** [comment]
I'm going to sit on the fence here.

Being an OpenStack person I'd rather this was hosted on opendev.org just because that'd reduce the mental gymnastics I need to do to work on it (Github is new to me).  Having said that moving it to opendev wont actually significantly alter the amount of time I have for working on this project.

I think what would help is defining expectations on code and review style.  Is a single approval enough?  How long do we leave approved changes before we time out and just merge them?

Having enhanced CI would be good, and this is where opendev would give us an advantage as the capabilities of zuul are much more than travis.  Also IIUC travis is the only single-point-of-failure we have in that only @ErwanAliasr1 can fix it.

**Comment by elfosardo** [comment]
thanks all for your valued comments, I'm positively surprised by all the participation, and despite how this ends, I'm quite happy about it :)

@tbreeds  it won't alter the amount of time you have for this project, but it will alter the number of people working on it, as it will be backed up by the entire Openstack community, with the Ironic team in first line (I expect retaliation for this :D ), as very interested in keeping the project alive, for the reasons I explained before.

My point in all this discussion is barely the change of organization, but keeping the project not just in a "surviving" state, but alive, and again I think the better way to do it is to put it in a place where it will get a lot of visibility and attention, plus all the technical benefits (zuul CI, gerrit, reviewing system, code standards, etc.).

**Comment by dtantsur** [comment]
I think we're good now, we can discuss moving to opendev.org separately.
